# Generated by Django 3.1.3 on 2020-11-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20201103_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='day',
            new_name='date',
        ),
    ]
